gateway:
  host: http://localhost:8080

spring:
  application:
    # eureka server 上註冊的名稱
    name: auth-service
  datasource:
    url: "jdbc:postgresql://postgres:5432/AlgoCrack"
    username: postgres
    password: 32865417
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: http://localhost:8080/login/oauth2/code/google

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://eureka-server:8761/eureka}
    registerWithEureka: true
    fetchRegistry: true
  instance:
    prefer-ip-address: true
