server:
  port: 8081

spring:
  application:
    # eureka server 上註冊的名稱
    name: auth-service
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: xxx
            clientSecret: xxx
            scope: 
            - profile
            - email
      
  datasource:
    url: "jdbc:postgresql://localhost:5432/AlgoCrack"
    username: postgres
    password: 32865417
    driver-class-name: org.postgresql.Driver

hello:
  english: Greetings from Spring Boot!
  chinese: 來自 Spring Boot 的問候！

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    registerWithEureka: true
    fetchRegistry: true
  instance:
    prefer-ip-address: true
