server:
  port: 8082

gateway:
  host: http://localhost:8081

spring:
  application:
    # eureka server 上註冊的名稱
    name: problem-service
  datasource:
    url: "jdbc:postgresql://localhost:5432/AlgoCrack"
    username: postgres
    password: 32865417
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: localhost
      port: 6379

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    registerWithEureka: true
    fetchRegistry: true
  instance:
    prefer-ip-address: true

