server:
  port: 8080

spring:
  application:
    # eureka server 上註冊的名稱
    name: api-gateway-service
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
      - id: auth-service
        uri: lb://AUTH-SERVICE
        predicates:
        - Path=/oauth2/**
      - id: auth-service-test
        uri: lb://AUTH-SERVICE
        predicates:
        - Path=/auth/**

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    registerWithEureka: true
    fetchRegistry: true
  instance:
    prefer-ip-address: true
