server:
  port: 8080

spring:
  application:
    name: api-gate-service
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
      - id: auth-service
        uri: http://localhost:8081
        predicates:
        - Path=/oauth2/**

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    registerWithEureka: true
    fetchRegistry: true
  instance:
    prefer-ip-address: true
